---
title: "file-name-modifier"
author: "Vishal Balaji"
date: "10/29/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

## If a package is installed, it will be loaded. If any 
## are not, the missing package(s) will be installed 
## from CRAN and then loaded.
## First specify the packages of interest
packages = c("tidyverse", "pdftools",
             "filesstrings", "stringi", "svDialogs", "rlist")

## Now load or install&load all
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)

## Working directory function
get_user_wd <- function() {
  dir <- dlg_input("Paste the data directory path", "H:\\Records Vault")$res
  
  dir <- gsub("\\", "/", dir, fixed=TRUE)
  if (length(dir) > 0 | is.null(dir)) {
    return(dir)
  } else {
    message("The working directory has been set to the default directory: 'H:\\Records Vault'")
    dir <- "H:/Records Vault"
    return(dir)
  }
}

directory <- get_user_wd()

knitr::opts_knit$set(root.dir = directory)
directory

dir.create("temp/")
```

```{r test-file-generator, eval=FALSE, message=FALSE, include=FALSE, results=FALSE}
# The test files will be generated in the newly set working directory

#SSN
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 1:2, output = "TEST_LAST_FIRST_MIDDLE_555444333.PDF")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 3:4, output = "TEST_LAST_FIRST_MIDDLE_555444333001.PDF")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 5:5, output = "TEST_LAST_FIRST_MIDDLE_555444333002.PDF")

#SSN
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 1:2, output = "TEST_LAST_FIRST_MIDDLE_555444333.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 3:4, output = "TEST_LAST_FIRST_MIDDLE_555444333_1of2.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 5:5, output = "TEST_LAST_FIRST_MIDDLE_555444333_2of2.pdf")

#SID 
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 1:2, output = "TEST_LAST_FIRST_MIDDLE_SID123410.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 3:4, output = "TEST_LAST_FIRST_MIDDLE_SID123410001.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 5:5, output = "TEST_LAST_FIRST_MIDDLE_SID123410002.pdf")

pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 5:5, output = "TEST_LAST_FIRST_SIDDHART_SID223410.pdf")
```

```{r extension-corrector}
files <- list.files(pattern="*.PDF") # Gets the names of the files with .PDF extensions
newfiles <- gsub(".PDF$", ".pdf", files) # Creates new file names with replaced .pdf extension
if (length(newfiles) != 0) {
  successPDF <- file.rename(files, newfiles) # renames the files
  all(successPDF)
} else {
  message("No files needed a .PDF to .pdf extension change.")
}
```

```{r ssn-name}
## Add SSN after SSN number
files <- list.files(pattern="(*_\\d{9}.pdf)")
newfiles <- gsub(".pdf$", "SSN.pdf", files)
if (length(newfiles) > 0) {
  successSSN <- file.rename(files, newfiles) # renames the files
  all(successSSN)
} else {
  message("No files needed the 'SSN' code after the SSN number")
}

## Add SSN after SSN number and before copy number
files <- list.files(pattern="(*_\\d{12}.pdf)")
newfiles <- files
stri_sub(newfiles, -7, -8) <- c("SSN")

if (length(newfiles) > 0) {
  successSSNcopy <- file.rename(files, newfiles) # renames the files
  all(successSSNcopy)
} else {
  message("No files needed the 'SSN' code after the SSN number but before copy number")
}

## Add SSN after SSN and before n of n copy number

files <- list.files(pattern="(*_\\d{9}_\\dof\\d.pdf$)|(*_\\d{9}_\\d0f\\d.pdf$)|(*_\\d{9}_\\dOf\\d.pdf$)")
newfiles <- files
stri_sub(newfiles, -9, -10) <- c("SSN")

if (length(newfiles) > 0) {
  successSSNnofn <- file.rename(files, newfiles) # renames the files
  all(successSSNnofn)
} else {
  message("No files needed the 'SSN' code after the SSN number but before n of n copy number")
}
```

```{r sid-name}
## Change "SID" from before SID number to after SID number
files <- list.files(pattern="(*_SID\\d{6}.pdf)")
newfiles <- sub("(SID)(\\d{6})", "\\2\\1", files)
if (length(newfiles) > 0) {
  successSID <- file.rename(files, newfiles) # renames the files
  all(successSID)
} else {
  message("No files needed the 'SID' code order to be changed after SID number")
}


## Change "SID" from before SID number to 'after SID number and before copy number'
files <- list.files(pattern="(*_SID\\d{9}.pdf)")
newfiles <- sub("(SID)(\\d{6})(\\d{3})", "\\2\\1\\3", files)
if (length(newfiles) > 0) {
  successSIDcopy <- file.rename(files, newfiles) # renames the files
  all(successSIDcopy)
} else {
  message("No files needed the 'SID' code order to be changed after SID number but before copy number")
}
```


