---
title: "PDF Appender"
author: "Vishal Balaji"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

## If a package is installed, it will be loaded. If any 
## are not, the missing package(s) will be installed 
## from CRAN and then loaded.
## First specify the packages of interest
packages = c("tidyverse", "pdftools",
             "filesstrings", "stringi", "svDialogs", "rlist", "XML")

## Now load or install&load all
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)

## Working directory function
get_user_wd <- function() {
  dir <- dlg_input("Paste the data directory path", "H:\\Records Vault")$res
  
  dir <- gsub("\\", "/", dir, fixed=TRUE)
  if (length(dir) > 0 | is.null(dir)) {
    return(dir)
  } else {
    message("The working directory has been set to the default directory: 'H:\\Records Vault'")
    dir <- "H:/Records Vault"
    return(dir)
  }
}

directory <- get_user_wd()

knitr::opts_knit$set(root.dir = directory)
directory

dir.create("temp/")
dir.create("resources/")
if(!file.exists('resources/Office of records-simplecoverpage.pdf')){
      download.file("https://github.com/vishalbalaji3/records-office/raw/main/data/resources/Office%20of%20records-simplecoverpage.pdf", 'resources/Office of records-simplecoverpage.pdf', mode="wb")
    }

```

```{r setup-2}
# Initialization of the Appender

# Run this section in the given order

fileAppender <- function(og, append) {
  tempdir <- paste(getwd(), "/temp/", sep = "") # temp output directory for the combined files
  appendedFiles <- rep(NA, 0) # initializes an empty list
  
  # for loop for appending files
  if (length(og) == 0) {
    message("No files of this type need to be appended")
    return(appendedFiles)
  }
  
  for (fileName in og) {
    if(!file.exists(paste0(fileName, ".pdf"))){
      pdf_subset("resources/Office of records-simplecoverpage.pdf",
                 pages = 1:1, output = paste0(fileName, ".pdf"))
    }
    temp <- str_extract(append, paste(fileName, "\\d{4}.pdf", sep = ""))
    temp <- temp[!is.na(temp)]
    fileName <- paste(fileName, ".pdf", sep = "")
    pdftools::pdf_combine(c(fileName, temp), output = paste(tempdir, fileName, sep = ""))
    appendedFiles <- append(appendedFiles, fileName)
  }
  
  # moves file to working directory
  filesstrings::move_files(paste(getwd(), "/temp/", appendedFiles, sep = ""), getwd(), overwrite = TRUE)
  return(appendedFiles)
}

# Deletes all the copy files.
fileDeleter <- function(toAppend) {
  deletedFiles <- rep(NA, 0) # initializes an empty list
  for (fn in toAppend) {
    if (file.exists(fn)) {
      file.remove(fn)
      deletedFiles <- append(deletedFiles, fn)
    }
  }
  filesDeleted_success <- identical(deletedFiles, toAppend)
  if (filesDeleted_success) {
    message("Successfully deleted files")
  }
  return(deletedFiles)
}
```


```{r test-file-generator, message=FALSE, results=FALSE}
# The test files will be generated in the newly set working directory

## SSN
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 1:3, output = "TEST_LAST_FIRST_333221234SSN.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 4:5, output = "TEST_LAST_FIRST_333221234SSN0001.pdf")

pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 1:2, output = "TEST_LAST_FIRST_MIDDLE_333222341SSN.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 3:4, output = "TEST_LAST_FIRST_MIDDLE_333222341SSN0001.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 5:5, output = "TEST_LAST_FIRST_MIDDLE_333222341SSN0002.pdf")

## SID
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 1:2, output = "TEST_LAST_FIRST_MIDDLE_123410SID.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 3:4, output = "TEST_LAST_FIRST_MIDDLE_123410SID0001.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 5:5, output = "TEST_LAST_FIRST_MIDDLE_123410SID0002.pdf")

## name only
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 1:2, output = "TEST_LAST_FIRST_MIDDLE.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 3:4, output = "TEST_LAST_FIRST_MIDDLE0001.pdf")
pdf_subset('https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf',
           pages = 5:5, output = "TEST_LAST_FIRST_MIDDLE0002.pdf")
```

```{r ssn-appender}
# toAppend_ssn is a list that contains the names of all the files that need to be appended (copies ending with the 001, 002,...) to the original/root file.
# ogFiles_ssn is a list that contains the names of all the original/root files. It is obtained from the toAppend_ssn list.
# filesAppended_SSN and filesDeleted_SSN are lists that show what files have been combined and what files have been deleted, respectively.

toAppend_ssn <- dir(pattern = "(\\d{9}SSN\\d{4})", recursive = TRUE, all.files = TRUE, full.names = FALSE)
ogFiles_ssn <- unique(str_extract(toAppend_ssn, "(^.*SSN)"))

filesAppended_SSN <- fileAppender(ogFiles_ssn, toAppend_ssn)

# RUN ONLY AFTER APPENDING #
filesDeleted_SSN <- fileDeleter(toAppend_ssn)
# RUN ONLY AFTER APPENDING #
```

```{r sid-appender}
# same variable naming format as Append SSN files section

toAppend_sid <- dir(pattern = "(\\d{6}SID\\d{4})", recursive = TRUE, all.files = TRUE, full.names = FALSE)
ogFiles_sid <- unique(str_extract(toAppend_sid, "(^.*SID)"))

filesAppended_SID <- fileAppender(ogFiles_sid, toAppend_sid)

# RUN ONLY AFTER APPENDING #
filesDeleted_SID <- fileDeleter(toAppend_sid)
# RUN ONLY AFTER APPENDING #
```

```{r name-only-appender}
toAppend_name <- dir(pattern = "(_[[:alpha:]]*\\d{4}.pdf$)", recursive = TRUE, all.files = TRUE, full.names = FALSE)
ogFiles_name <- unique(str_extract(toAppend_name, "(\\D*)"))

filesAppended_name <- fileAppender(ogFiles_name, toAppend_name)
filesDeleted_name <- fileDeleter(toAppend_name)
```

```{r deleted-files-list}
deletedFiles <- rep(NA, 0)
deleteVar <- c(filesDeleted_SSN, filesDeleted_SID, filesDeleted_name)
deletedFiles <- append(deletedFiles, deleteVar)

appendedFiles <- c(filesAppended_SSN, filesAppended_SID, filesAppended_name)

rm(deleteVar,filesDeleted_SSN, filesDeleted_SID, filesDeleted_name, filesAppended_name, filesAppended_SSN, filesAppended_SID, ogFiles_name, ogFiles_ssn, ogFiles_sid, toAppend_name, toAppend_ssn, toAppend_sid)

dir.create("log/")

if (length(appendedFiles) > 0) {
  list.save(appendedFiles, paste("log/appendedFiles",format(Sys.time(), "%Y-%m-%d_%H%M"), ".yaml", sep = ""))
} else {
  message("\nNo file were appended during this session")
}

if (length(deletedFiles) > 0) {
  list.save(deletedFiles, paste("log/deletedFiles",format(Sys.time(), "%Y-%m-%d_%H%M"), ".yaml", sep = ""))
} else {
  message("No file were appended during this session")
}

```

